version: "3.9"
services:
  web-server:
    container_name: web-server
    build: .
    image: node-boilerplate:v1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
